########################################################################################################################
### For homeworks
### Get all documents
GET http://localhost:3000/api/homeworks

### Get one document by Id
GET http://localhost:3000/api/homeworks/5f6ff3d34566190b10831348

### Get one document by Id (created by me)
GET http://localhost:3000/api/homeworks/5f8b8f7d71cc4e23e4f82c64

### Create new document
POST http://localhost:3000/api/homeworks
Content-Type: application/json

{
  "subject": {
    "teacher_name": {
      "first": "New",
      "last": "Newpppppppp"
    },
    "title": "New"
  },
  "semester": {
    "year": 2779,
    "name": "New"
  },
  "school": {
    "name": "New",
    "address": "New",
    "logo": "https://www.nscc.ca/img/designelements/header/new.png"
  },
  "title": "New",
  "score": 100,
  "due_date": "2020-08-11T21:06:42.000Z",
  "submit": [
    {
      "seq_no": 1,
      "title": "New",
      "text_content": "New1."
    },
    {
      "seq_no": 2,
      "title": "New",
      "text_content": "New2."
    },
    {
      "seq_no": 3,
      "title": "New",
      "text_content": "New3."
    }
  ],
  "progress": 0
}

### Update an existing document by Id
PUT http://localhost:3000/api/homeworks/5f8b8f7d71cc4e23e4f82c64
Content-Type: application/json

{
  "subject": {
    "teacher_name": {
      "first": "ReplacedByPut",
      "last": "ReplacedByPut"
    },
    "title": "ReplacedByPut"
  },
  "semester": {
    "year": 2777,
    "name": "ReplacedByPut"
  },
  "school": {
    "name": "ReplacedByPut",
    "address": "ReplacedByPut",
    "logo": "https://www.nscc.ca/img/designelements/header/ReplacedByPut.png"
  },
  "title": "ReplacedByPut",
  "score": 100,
  "due_date": "2020-08-11T21:06:42.000Z",
  "submit": [
    {
      "seq_no": 1,
      "title": "ReplacedByPut",
      "text_content": "New1."
    },
    {
      "seq_no": 2,
      "title": "ReplacedByPut",
      "text_content": "New2."
    },
    {
      "seq_no": 3,
      "title": "ReplacedByPut",
      "text_content": "New3."
    }
  ],
  "progress": 0
}

### Delete an existing document by Id
DELETE http://localhost:3000/api/homeworks/5f8bc84d0fca612af49d278e

########################################################################################################################
### For users
### Create new document
POST http://localhost:3000/api/users/register
Content-Type: application/json

{
  "firstName": "Newwwwwwwwwwwwttweeeeefffffffffttwww",
  "lastName": "Newlasthhhhhhhhhhhht",
  "email": "test1@gmail.com",
  "password": "password123"
}

### login with email and password
POST http://localhost:3000/api/users/login
Content-Type: application/json

{
  "email": "test@gmail.com",
  "password": "password123"
}
